var numbers = [2, 3, 4, 5, 6];
numbers.push("four");
console.log(numbers);
var names = ["rani", "sudeep", "gita"];
console.log(names);
var mixed = [1, "jyoti", 20, "piku"];
console.log(mixed);
var fruits = ["banana", "apple", "mango"];
fruits.push("pear");
console.log(fruits);
var matrix = [[1, 2, 3], [4, 5, 6]];
console.log(matrix);
